# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 11.0.x
    - name: Restore dependencies
      run: dotnet restore CoreProxy.Server.Orleans
    - name: Install ARM64 cross compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y clang gcc-aarch64-linux-gnu g++-aarch64-linux-gnu binutils-aarch64-linux-gnu
    - name: Publish
      run: |
        dotnet publish CoreProxy.Server.Orleans -c Release -r linux-x64
        dotnet publish CoreProxy.Server.Orleans -c Release -r linux-arm64 -p:CppCompilerAndLinker=clang
    - name: Zip
      run: |
        cd ${{ github.workspace }}/CoreProxy.Server.Orleans/bin/Release/net11.0/linux-x64
        zip -r publish-linux-x64.zip publish
        cd ${{ github.workspace }}/CoreProxy.Server.Orleans/bin/Release/net11.0/linux-arm64
        zip -r publish-linux-arm64.zip publish
    - name: Create GitHub release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: latest
        prerelease: false
        title: latest
        files: |
          ${{ github.workspace }}/CoreProxy.Server.Orleans/bin/Release/net11.0/linux-x64/publish-linux-x64.zip
          ${{ github.workspace }}/CoreProxy.Server.Orleans/bin/Release/net11.0/linux-arm64/publish-linux-arm64.zip

