# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore CoreProxy.Server.Orleans
    - name: Publish
      run: dotnet publish CoreProxy.Server.Orleans -r linux-x64
    # - name: upload result
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: my-artifact
    #     path: ${{ github.workspace }}/bin/Release/net8.0/linux-x64/publish
    - name: Zip
      run: |
        cd ${{ github.workspace }}/CoreProxy.Server.Orleans/bin/Release/net9.0/linux-x64
        zip -r publish-linux-x64.zip publish
    - name: Create GitHub release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: latest
        prerelease: false
        title: latest
        files: |
          ${{ github.workspace }}/CoreProxy.Server.Orleans/bin/Release/net9.0/linux-x64/publish-linux-x64.zip

